language: bash

services:
  - docker

before_script:
  - docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD

jobs:
  include:
    stage: push_master
    script:
      - docker build -t dantebarba/whatsmyhealth:latest .
      - docker push dantebarba/whatsmyhealth:latest
    if: branch = master
    stage: push_tag
    script: 
      - docker build -t dantebarba/whatsmyhealth:$TRAVIS_TAG .
      - docker push dantebarba/whatsmyhealth:$TRAVIS_TAG
    if: tag IS present
